#!/bin/sh

echo "Prepping Kernel image $1"
cd /home/ka/build/Kappa

echo "Removing old modules from Ramdisk tree"
rm -fr /home/ka/build/ramdisk/kappa-ramdisk/system/lib/*

echo "Copying Kernel drivers into Ramdisk (/system/lib)"
find . -name *.ko | xargs -i cp {} /home/ka/build/ramdisk/kappa-ramdisk/system/lib/ 

echo "Copying Wifi drivers into Ramdisk (/system/lib/modules)"
cd /home/ka/build/Kappa/compat-wireless-wl12xx/

find . -name wl12xx*.ko | xargs -i cp {} /home/ka/build/ramdisk/kappa-ramdisk/rek/modules/

cp ./compat/compat_firmware_class.ko /home/ka/build/ramdisk/kappa-ramdisk/rek/modules/
cp ./compat/compat.ko /home/ka/build/ramdisk/kappa-ramdisk/rek/modules/
cp ./net/wireless/cfg80211.ko /home/ka/build/ramdisk/kappa-ramdisk/rek/modules/
cp ./net/mac80211/mac80211.ko /home/ka/build/ramdisk/kappa-ramdisk/rek/modules/

cd /home/ka/build/ramdisk/kappa-ramdisk 
echo "Packaging Ramdisk"
rm ../kappa-ka-ramdisk.img
find . | cpio --quiet -H newc -o | gzip > ../kappa-ka-ramdisk.img 
cd /home/ka/build/Kappa/bootimg 
echo "Making image $1"
mkbootimg --kernel ../Kappa/arch/arm/boot/zImage --ramdisk ../ramdisk/kappa-ka-ramdisk.img --base 0x00200000 -o $1
ls -alrt $1
echo "Done"


