#!/bin/bash

echo "Making them all"
cd /home/ka/build/Kappa

echo "Cleaning before Mango build"
echo "Applying Mango defconfig"
mkdefmango
echo "Making Mango"
mkbuildmango


echo "Cleaning before Coconut build"
echo "Applying Coconut defconfig"
mkdefcoconut
echo "Making Coconut"
mkbuildcoconut

echo "Cleaning before Satsuma build"
echo "Applying Satsuma defconfig"
mkdefsatsuma
echo "Making Satsuma"
mkbuildsatsuma

echo "Cleaning before Smultron build"
echo "Applying Smultron defconfig"
mkdefsmultron
echo "Making Smultron"
mkbuildsmultron

echo "Done, I'll get some rest now"


