#!/bin/bash

echo "Prepping Kernel image $1"
cd /home/ka/build/Kappa

echo "Removing old modules from Ramdisk tree"
rm -fr /home/ka/build/ramdisk/kappa-cwm/system/lib/*

echo "Copying Kernel drivers into Ramdisk (/system/lib)"
find . -name *.ko | grep -v compat-wireless-wl12xx 
find . -name *.ko | grep -v compat-wireless-wl12xx | xargs -i cp {} /home/ka/build/ramdisk/kappa-cwm/system/lib/ 
mv /home/ka/build/ramdisk/kappa-cwm/system/lib/cifs.ko /home/ka/build/ramdisk/kappa-cwm/rek/modules
mv /home/ka/build/ramdisk/kappa-cwm/system/lib/ntfs.ko /home/ka/build/ramdisk/kappa-cwm/rek/modules
mv /home/ka/build/ramdisk/kappa-cwm/system/lib/fuse.ko /home/ka/build/ramdisk/kappa-cwm/rek/modules
mv /home/ka/build/ramdisk/kappa-cwm/system/lib/hfsplus.ko /home/ka/build/ramdisk/kappa-ramdisk/rek/modules

echo "Copying Wifi drivers into Ramdisk (/system/lib/modules)"
cd /home/ka/build/Kappa/compat-wireless-wl12xx/
find . -name wl12xx*.ko
find . -name wl12xx*.ko | xargs -i cp {} /home/ka/build/ramdisk/kappa-cwm/rek/modules/

echo "./compat/compat_firmware_class.ko"
cp ./compat/compat_firmware_class.ko /home/ka/build/ramdisk/kappa-cwm/rek/modules/
echo "./compat/compat.ko"
cp ./compat/compat.ko /home/ka/build/ramdisk/kappa-cwm/rek/modules/
echo "./net/wireless/cfg80211.ko"
cp ./net/wireless/cfg80211.ko /home/ka/build/ramdisk/kappa-cwm/rek/modules/
echo "./net/mac80211/mac80211.ko"
cp ./net/mac80211/mac80211.ko /home/ka/build/ramdisk/kappa-cwm/rek/modules/

cd /home/ka/build/ramdisk/kappa-cwm 
echo "Packaging CWM Ramdisk"
find . | cpio --quiet -H newc -o | lzma -7 > ../kappa-cwm.lzma

echo "Packaging TWRP Ramdisk"
cd /home/ka/build/ramdisk/twrp-ramdisk
find . | cpio --quiet -H newc -o | lzma -7 > /home/ka/build/ramdisk/kappa-twrp.lzma

echo "Packaging all Together"
cd /home/ka/build/ramdisk/initrdisk
rm /home/ka/build/ramdisk/initrdisk/rek/res/kappa-cwm.lzma
rm /home/ka/build/ramdisk/initrdisk/rek/res/kappa-twrp.lzma

cp ../kappa-cwm.lzma rek/res
cp ../kappa-twrp.lzma rek/res

rm ../kappa-ka-ramdisk.img
find . | cpio --quiet -H newc -o | lzma -7 > ../kappa-ka-ramdisk.img 
cd /home/ka/build/Kappa/bootimg 
echo "Making image $1"
mkbootimg --kernel ../arch/arm/boot/zImage --ramdisk ../../ramdisk/kappa-ka-ramdisk.img --base 0x00200000 -o $1
ls -alrt $1
echo "Done"


