#!/bin/bash

echo "Building the WLan Driver"
cd /home/ka/build/Kappa/compat-wireless-wl12xx
ARCH=arm CROSS_COMPILE=/home/ka/build/linaro/android-toolchain-eabi/bin/arm-eabi-  KLIB=/home/ka/build/Kappa KLIB_BUILD=/home/ka/build/Kappa make clean
./scripts/driver-select wl12xx
ARCH=arm CROSS_COMPILE=/home/ka/build/linaro/android-toolchain-eabi/bin/arm-eabi-  KLIB=/home/ka/build/Kappa KLIB_BUILD=/home/ka/build/Kappa make -j8 
find . -name *.ko | xargs -i /home/ka/build/linaro/android-toolchain-eabi/bin/arm-eabi-strip --strip-debug  {}

